// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_034() {
    double acc = Polynomial<334>::eval(0.5);
    acc += static_cast<double>(MetaSum<334ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<34, 35, 36, 37>::fold();
    acc += static_cast<double>(Grid<322>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 34.0);
    acc += regex_score("module 034 alpha42 beta tu34");
    return acc / 6.0;
}

}  // namespace cbor
