// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_085() {
    double acc = Polynomial<385>::eval(0.5);
    acc += static_cast<double>(MetaSum<385ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<85, 86, 87, 88>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 85.0);
    acc += regex_score("module 085 alpha42 beta tu85");
    return acc / 6.0;
}

}  // namespace cbor
