// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_020() {
    double acc = Polynomial<320>::eval(0.5);
    acc += static_cast<double>(MetaSum<320ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<20, 21, 22, 23>::fold();
    acc += static_cast<double>(Grid<324>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 20.0);
    acc += regex_score("module 020 alpha42 beta tu20");
    return acc / 6.0;
}

}  // namespace cbor
