// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_030() {
    double acc = Polynomial<330>::eval(0.5);
    acc += static_cast<double>(MetaSum<330ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<30, 31, 32, 33>::fold();
    acc += static_cast<double>(Grid<334>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 30.0);
    acc += regex_score("module 030 alpha42 beta tu30");
    return acc / 6.0;
}

}  // namespace cbor
