// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_047() {
    double acc = Polynomial<347>::eval(0.5);
    acc += static_cast<double>(MetaSum<347ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<47, 48, 49, 50>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 47.0);
    acc += regex_score("module 047 alpha42 beta tu47");
    return acc / 6.0;
}

}  // namespace cbor
