// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_002() {
    double acc = Polynomial<302>::eval(0.5);
    acc += static_cast<double>(MetaSum<302ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<2, 3, 4, 5>::fold();
    acc += static_cast<double>(Grid<322>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 2.0);
    acc += regex_score("module 002 alpha42 beta tu2");
    return acc / 6.0;
}

}  // namespace cbor
