// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_071() {
    double acc = Polynomial<371>::eval(0.5);
    acc += static_cast<double>(MetaSum<371ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<71, 72, 73, 74>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 71.0);
    acc += regex_score("module 071 alpha42 beta tu71");
    return acc / 6.0;
}

}  // namespace cbor
