// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_037() {
    double acc = Polynomial<337>::eval(0.5);
    acc += static_cast<double>(MetaSum<337ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<37, 38, 39, 40>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 37.0);
    acc += regex_score("module 037 alpha42 beta tu37");
    return acc / 6.0;
}

}  // namespace cbor
