// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_014() {
    double acc = Polynomial<314>::eval(0.5);
    acc += static_cast<double>(MetaSum<314ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<14, 15, 16, 17>::fold();
    acc += static_cast<double>(Grid<334>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 14.0);
    acc += regex_score("module 014 alpha42 beta tu14");
    return acc / 6.0;
}

}  // namespace cbor
