// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_021() {
    double acc = Polynomial<321>::eval(0.5);
    acc += static_cast<double>(MetaSum<321ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<21, 22, 23, 24>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 21.0);
    acc += regex_score("module 021 alpha42 beta tu21");
    return acc / 6.0;
}

}  // namespace cbor
