// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_057() {
    double acc = Polynomial<357>::eval(0.5);
    acc += static_cast<double>(MetaSum<357ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<57, 58, 59, 60>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 57.0);
    acc += regex_score("module 057 alpha42 beta tu57");
    return acc / 6.0;
}

}  // namespace cbor
