// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_004() {
    double acc = Polynomial<304>::eval(0.5);
    acc += static_cast<double>(MetaSum<304ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<4, 5, 6, 7>::fold();
    acc += static_cast<double>(Grid<324>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 4.0);
    acc += regex_score("module 004 alpha42 beta tu4");
    return acc / 6.0;
}

}  // namespace cbor
