// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_039() {
    double acc = Polynomial<339>::eval(0.5);
    acc += static_cast<double>(MetaSum<339ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<39, 40, 41, 42>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 39.0);
    acc += regex_score("module 039 alpha42 beta tu39");
    return acc / 6.0;
}

}  // namespace cbor
