// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_024() {
    double acc = Polynomial<324>::eval(0.5);
    acc += static_cast<double>(MetaSum<324ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<24, 25, 26, 27>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 24.0);
    acc += regex_score("module 024 alpha42 beta tu24");
    return acc / 6.0;
}

}  // namespace cbor
