// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_074() {
    double acc = Polynomial<374>::eval(0.5);
    acc += static_cast<double>(MetaSum<374ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<74, 75, 76, 77>::fold();
    acc += static_cast<double>(Grid<330>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 74.0);
    acc += regex_score("module 074 alpha42 beta tu74");
    return acc / 6.0;
}

}  // namespace cbor
