// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_016() {
    double acc = Polynomial<316>::eval(0.5);
    acc += static_cast<double>(MetaSum<316ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<16, 17, 18, 19>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 16.0);
    acc += regex_score("module 016 alpha42 beta tu16");
    return acc / 6.0;
}

}  // namespace cbor
