// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_065() {
    double acc = Polynomial<365>::eval(0.5);
    acc += static_cast<double>(MetaSum<365ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<65, 66, 67, 68>::fold();
    acc += static_cast<double>(Grid<321>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 65.0);
    acc += regex_score("module 065 alpha42 beta tu65");
    return acc / 6.0;
}

}  // namespace cbor
