// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_018() {
    double acc = Polynomial<318>::eval(0.5);
    acc += static_cast<double>(MetaSum<318ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<18, 19, 20, 21>::fold();
    acc += static_cast<double>(Grid<322>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 18.0);
    acc += regex_score("module 018 alpha42 beta tu18");
    return acc / 6.0;
}

}  // namespace cbor
