// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_087() {
    double acc = Polynomial<387>::eval(0.5);
    acc += static_cast<double>(MetaSum<387ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<87, 88, 89, 90>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 87.0);
    acc += regex_score("module 087 alpha42 beta tu87");
    return acc / 6.0;
}

}  // namespace cbor
