// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_083() {
    double acc = Polynomial<383>::eval(0.5);
    acc += static_cast<double>(MetaSum<383ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<83, 84, 85, 86>::fold();
    acc += static_cast<double>(Grid<323>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 83.0);
    acc += regex_score("module 083 alpha42 beta tu83");
    return acc / 6.0;
}

}  // namespace cbor
