// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_063() {
    double acc = Polynomial<363>::eval(0.5);
    acc += static_cast<double>(MetaSum<363ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<63, 64, 65, 66>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 63.0);
    acc += regex_score("module 063 alpha42 beta tu63");
    return acc / 6.0;
}

}  // namespace cbor
