// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_001() {
    double acc = Polynomial<301>::eval(0.5);
    acc += static_cast<double>(MetaSum<301ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<1, 2, 3, 4>::fold();
    acc += static_cast<double>(Grid<321>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 1.0);
    acc += regex_score("module 001 alpha42 beta tu1");
    return acc / 6.0;
}

}  // namespace cbor
