// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_027() {
    double acc = Polynomial<327>::eval(0.5);
    acc += static_cast<double>(MetaSum<327ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<27, 28, 29, 30>::fold();
    acc += static_cast<double>(Grid<331>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 27.0);
    acc += regex_score("module 027 alpha42 beta tu27");
    return acc / 6.0;
}

}  // namespace cbor
