// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_043() {
    double acc = Polynomial<343>::eval(0.5);
    acc += static_cast<double>(MetaSum<343ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<43, 44, 45, 46>::fold();
    acc += static_cast<double>(Grid<331>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 43.0);
    acc += regex_score("module 043 alpha42 beta tu43");
    return acc / 6.0;
}

}  // namespace cbor
