// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_040() {
    double acc = Polynomial<340>::eval(0.5);
    acc += static_cast<double>(MetaSum<340ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<40, 41, 42, 43>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 40.0);
    acc += regex_score("module 040 alpha42 beta tu40");
    return acc / 6.0;
}

}  // namespace cbor
