// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_076() {
    double acc = Polynomial<376>::eval(0.5);
    acc += static_cast<double>(MetaSum<376ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<76, 77, 78, 79>::fold();
    acc += static_cast<double>(Grid<332>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 76.0);
    acc += regex_score("module 076 alpha42 beta tu76");
    return acc / 6.0;
}

}  // namespace cbor
