// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_066() {
    double acc = Polynomial<366>::eval(0.5);
    acc += static_cast<double>(MetaSum<366ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<66, 67, 68, 69>::fold();
    acc += static_cast<double>(Grid<322>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 66.0);
    acc += regex_score("module 066 alpha42 beta tu66");
    return acc / 6.0;
}

}  // namespace cbor
