// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_086() {
    double acc = Polynomial<386>::eval(0.5);
    acc += static_cast<double>(MetaSum<386ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<86, 87, 88, 89>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 86.0);
    acc += regex_score("module 086 alpha42 beta tu86");
    return acc / 6.0;
}

}  // namespace cbor
