// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_007() {
    double acc = Polynomial<307>::eval(0.5);
    acc += static_cast<double>(MetaSum<307ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<7, 8, 9, 10>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 7.0);
    acc += regex_score("module 007 alpha42 beta tu7");
    return acc / 6.0;
}

}  // namespace cbor
