// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_052() {
    double acc = Polynomial<352>::eval(0.5);
    acc += static_cast<double>(MetaSum<352ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<52, 53, 54, 55>::fold();
    acc += static_cast<double>(Grid<324>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 52.0);
    acc += regex_score("module 052 alpha42 beta tu52");
    return acc / 6.0;
}

}  // namespace cbor
