// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_041() {
    double acc = Polynomial<341>::eval(0.5);
    acc += static_cast<double>(MetaSum<341ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<41, 42, 43, 44>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 41.0);
    acc += regex_score("module 041 alpha42 beta tu41");
    return acc / 6.0;
}

}  // namespace cbor
