// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_008() {
    double acc = Polynomial<308>::eval(0.5);
    acc += static_cast<double>(MetaSum<308ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<8, 9, 10, 11>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 8.0);
    acc += regex_score("module 008 alpha42 beta tu8");
    return acc / 6.0;
}

}  // namespace cbor
