// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_050() {
    double acc = Polynomial<350>::eval(0.5);
    acc += static_cast<double>(MetaSum<350ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<50, 51, 52, 53>::fold();
    acc += static_cast<double>(Grid<322>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 50.0);
    acc += regex_score("module 050 alpha42 beta tu50");
    return acc / 6.0;
}

}  // namespace cbor
