// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_088() {
    double acc = Polynomial<388>::eval(0.5);
    acc += static_cast<double>(MetaSum<388ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<88, 89, 90, 91>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 88.0);
    acc += regex_score("module 088 alpha42 beta tu88");
    return acc / 6.0;
}

}  // namespace cbor
