// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_006() {
    double acc = Polynomial<306>::eval(0.5);
    acc += static_cast<double>(MetaSum<306ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<6, 7, 8, 9>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 6.0);
    acc += regex_score("module 006 alpha42 beta tu6");
    return acc / 6.0;
}

}  // namespace cbor
