// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_000() {
    double acc = Polynomial<300>::eval(0.5);
    acc += static_cast<double>(MetaSum<300ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<0, 1, 2, 3>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 0.0);
    acc += regex_score("module 000 alpha42 beta tu0");
    return acc / 6.0;
}

}  // namespace cbor
