// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_012() {
    double acc = Polynomial<312>::eval(0.5);
    acc += static_cast<double>(MetaSum<312ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<12, 13, 14, 15>::fold();
    acc += static_cast<double>(Grid<332>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 12.0);
    acc += regex_score("module 012 alpha42 beta tu12");
    return acc / 6.0;
}

}  // namespace cbor
