// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_075() {
    double acc = Polynomial<375>::eval(0.5);
    acc += static_cast<double>(MetaSum<375ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<75, 76, 77, 78>::fold();
    acc += static_cast<double>(Grid<331>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 75.0);
    acc += regex_score("module 075 alpha42 beta tu75");
    return acc / 6.0;
}

}  // namespace cbor
