// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_077() {
    double acc = Polynomial<377>::eval(0.5);
    acc += static_cast<double>(MetaSum<377ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<77, 78, 79, 80>::fold();
    acc += static_cast<double>(Grid<333>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 77.0);
    acc += regex_score("module 077 alpha42 beta tu77");
    return acc / 6.0;
}

}  // namespace cbor
