// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_009() {
    double acc = Polynomial<309>::eval(0.5);
    acc += static_cast<double>(MetaSum<309ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<9, 10, 11, 12>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 9.0);
    acc += regex_score("module 009 alpha42 beta tu9");
    return acc / 6.0;
}

}  // namespace cbor
