// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_031() {
    double acc = Polynomial<331>::eval(0.5);
    acc += static_cast<double>(MetaSum<331ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<31, 32, 33, 34>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 31.0);
    acc += regex_score("module 031 alpha42 beta tu31");
    return acc / 6.0;
}

}  // namespace cbor
