// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_038() {
    double acc = Polynomial<338>::eval(0.5);
    acc += static_cast<double>(MetaSum<338ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<38, 39, 40, 41>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 38.0);
    acc += regex_score("module 038 alpha42 beta tu38");
    return acc / 6.0;
}

}  // namespace cbor
