// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_010() {
    double acc = Polynomial<310>::eval(0.5);
    acc += static_cast<double>(MetaSum<310ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<10, 11, 12, 13>::fold();
    acc += static_cast<double>(Grid<330>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 10.0);
    acc += regex_score("module 010 alpha42 beta tu10");
    return acc / 6.0;
}

}  // namespace cbor
