// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_080() {
    double acc = Polynomial<380>::eval(0.5);
    acc += static_cast<double>(MetaSum<380ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<80, 81, 82, 83>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 80.0);
    acc += regex_score("module 080 alpha42 beta tu80");
    return acc / 6.0;
}

}  // namespace cbor
