// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_055() {
    double acc = Polynomial<355>::eval(0.5);
    acc += static_cast<double>(MetaSum<355ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<55, 56, 57, 58>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 55.0);
    acc += regex_score("module 055 alpha42 beta tu55");
    return acc / 6.0;
}

}  // namespace cbor
