// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_058() {
    double acc = Polynomial<358>::eval(0.5);
    acc += static_cast<double>(MetaSum<358ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<58, 59, 60, 61>::fold();
    acc += static_cast<double>(Grid<330>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 58.0);
    acc += regex_score("module 058 alpha42 beta tu58");
    return acc / 6.0;
}

}  // namespace cbor
