// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_054() {
    double acc = Polynomial<354>::eval(0.5);
    acc += static_cast<double>(MetaSum<354ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<54, 55, 56, 57>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 54.0);
    acc += regex_score("module 054 alpha42 beta tu54");
    return acc / 6.0;
}

}  // namespace cbor
