// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_073() {
    double acc = Polynomial<373>::eval(0.5);
    acc += static_cast<double>(MetaSum<373ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<73, 74, 75, 76>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 73.0);
    acc += regex_score("module 073 alpha42 beta tu73");
    return acc / 6.0;
}

}  // namespace cbor
