// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_015() {
    double acc = Polynomial<315>::eval(0.5);
    acc += static_cast<double>(MetaSum<315ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<15, 16, 17, 18>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 15.0);
    acc += regex_score("module 015 alpha42 beta tu15");
    return acc / 6.0;
}

}  // namespace cbor
