// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_059() {
    double acc = Polynomial<359>::eval(0.5);
    acc += static_cast<double>(MetaSum<359ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<59, 60, 61, 62>::fold();
    acc += static_cast<double>(Grid<331>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 59.0);
    acc += regex_score("module 059 alpha42 beta tu59");
    return acc / 6.0;
}

}  // namespace cbor
