// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_092() {
    double acc = Polynomial<392>::eval(0.5);
    acc += static_cast<double>(MetaSum<392ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<92, 93, 94, 95>::fold();
    acc += static_cast<double>(Grid<332>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 92.0);
    acc += regex_score("module 092 alpha42 beta tu92");
    return acc / 6.0;
}

}  // namespace cbor
