// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_093() {
    double acc = Polynomial<393>::eval(0.5);
    acc += static_cast<double>(MetaSum<393ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<93, 94, 95, 96>::fold();
    acc += static_cast<double>(Grid<333>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 93.0);
    acc += regex_score("module 093 alpha42 beta tu93");
    return acc / 6.0;
}

}  // namespace cbor
