// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_079() {
    double acc = Polynomial<379>::eval(0.5);
    acc += static_cast<double>(MetaSum<379ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<79, 80, 81, 82>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 79.0);
    acc += regex_score("module 079 alpha42 beta tu79");
    return acc / 6.0;
}

}  // namespace cbor
