// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_005() {
    double acc = Polynomial<305>::eval(0.5);
    acc += static_cast<double>(MetaSum<305ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<5, 6, 7, 8>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 5.0);
    acc += regex_score("module 005 alpha42 beta tu5");
    return acc / 6.0;
}

}  // namespace cbor
