// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_095() {
    double acc = Polynomial<395>::eval(0.5);
    acc += static_cast<double>(MetaSum<395ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<95, 96, 97, 98>::fold();
    acc += static_cast<double>(Grid<335>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 95.0);
    acc += regex_score("module 095 alpha42 beta tu95");
    return acc / 6.0;
}

}  // namespace cbor
