// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_051() {
    double acc = Polynomial<351>::eval(0.5);
    acc += static_cast<double>(MetaSum<351ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<51, 52, 53, 54>::fold();
    acc += static_cast<double>(Grid<323>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 51.0);
    acc += regex_score("module 051 alpha42 beta tu51");
    return acc / 6.0;
}

}  // namespace cbor
