// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_032() {
    double acc = Polynomial<332>::eval(0.5);
    acc += static_cast<double>(MetaSum<332ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<32, 33, 34, 35>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 32.0);
    acc += regex_score("module 032 alpha42 beta tu32");
    return acc / 6.0;
}

}  // namespace cbor
