// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_003() {
    double acc = Polynomial<303>::eval(0.5);
    acc += static_cast<double>(MetaSum<303ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<3, 4, 5, 6>::fold();
    acc += static_cast<double>(Grid<323>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 3.0);
    acc += regex_score("module 003 alpha42 beta tu3");
    return acc / 6.0;
}

}  // namespace cbor
