// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_089() {
    double acc = Polynomial<389>::eval(0.5);
    acc += static_cast<double>(MetaSum<389ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<89, 90, 91, 92>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 89.0);
    acc += regex_score("module 089 alpha42 beta tu89");
    return acc / 6.0;
}

}  // namespace cbor
