// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_053() {
    double acc = Polynomial<353>::eval(0.5);
    acc += static_cast<double>(MetaSum<353ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<53, 54, 55, 56>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 53.0);
    acc += regex_score("module 053 alpha42 beta tu53");
    return acc / 6.0;
}

}  // namespace cbor
