// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_056() {
    double acc = Polynomial<356>::eval(0.5);
    acc += static_cast<double>(MetaSum<356ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<56, 57, 58, 59>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 56.0);
    acc += regex_score("module 056 alpha42 beta tu56");
    return acc / 6.0;
}

}  // namespace cbor
