// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_048() {
    double acc = Polynomial<348>::eval(0.5);
    acc += static_cast<double>(MetaSum<348ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<48, 49, 50, 51>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 48.0);
    acc += regex_score("module 048 alpha42 beta tu48");
    return acc / 6.0;
}

}  // namespace cbor
