// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_046() {
    double acc = Polynomial<346>::eval(0.5);
    acc += static_cast<double>(MetaSum<346ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<46, 47, 48, 49>::fold();
    acc += static_cast<double>(Grid<334>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 46.0);
    acc += regex_score("module 046 alpha42 beta tu46");
    return acc / 6.0;
}

}  // namespace cbor
