// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_019() {
    double acc = Polynomial<319>::eval(0.5);
    acc += static_cast<double>(MetaSum<319ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<19, 20, 21, 22>::fold();
    acc += static_cast<double>(Grid<323>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 19.0);
    acc += regex_score("module 019 alpha42 beta tu19");
    return acc / 6.0;
}

}  // namespace cbor
