// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_062() {
    double acc = Polynomial<362>::eval(0.5);
    acc += static_cast<double>(MetaSum<362ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<62, 63, 64, 65>::fold();
    acc += static_cast<double>(Grid<334>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 62.0);
    acc += regex_score("module 062 alpha42 beta tu62");
    return acc / 6.0;
}

}  // namespace cbor
