// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_070() {
    double acc = Polynomial<370>::eval(0.5);
    acc += static_cast<double>(MetaSum<370ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<70, 71, 72, 73>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 70.0);
    acc += regex_score("module 070 alpha42 beta tu70");
    return acc / 6.0;
}

}  // namespace cbor
