// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_017() {
    double acc = Polynomial<317>::eval(0.5);
    acc += static_cast<double>(MetaSum<317ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<17, 18, 19, 20>::fold();
    acc += static_cast<double>(Grid<321>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 17.0);
    acc += regex_score("module 017 alpha42 beta tu17");
    return acc / 6.0;
}

}  // namespace cbor
