// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_023() {
    double acc = Polynomial<323>::eval(0.5);
    acc += static_cast<double>(MetaSum<323ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<23, 24, 25, 26>::fold();
    acc += static_cast<double>(Grid<327>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 23.0);
    acc += regex_score("module 023 alpha42 beta tu23");
    return acc / 6.0;
}

}  // namespace cbor
