// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_022() {
    double acc = Polynomial<322>::eval(0.5);
    acc += static_cast<double>(MetaSum<322ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<22, 23, 24, 25>::fold();
    acc += static_cast<double>(Grid<326>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 22.0);
    acc += regex_score("module 022 alpha42 beta tu22");
    return acc / 6.0;
}

}  // namespace cbor
