// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_025() {
    double acc = Polynomial<325>::eval(0.5);
    acc += static_cast<double>(MetaSum<325ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<25, 26, 27, 28>::fold();
    acc += static_cast<double>(Grid<329>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 25.0);
    acc += regex_score("module 025 alpha42 beta tu25");
    return acc / 6.0;
}

}  // namespace cbor
