// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_081() {
    double acc = Polynomial<381>::eval(0.5);
    acc += static_cast<double>(MetaSum<381ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<81, 82, 83, 84>::fold();
    acc += static_cast<double>(Grid<321>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 81.0);
    acc += regex_score("module 081 alpha42 beta tu81");
    return acc / 6.0;
}

}  // namespace cbor
