// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_028() {
    double acc = Polynomial<328>::eval(0.5);
    acc += static_cast<double>(MetaSum<328ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<28, 29, 30, 31>::fold();
    acc += static_cast<double>(Grid<332>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 28.0);
    acc += regex_score("module 028 alpha42 beta tu28");
    return acc / 6.0;
}

}  // namespace cbor
