// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_091() {
    double acc = Polynomial<391>::eval(0.5);
    acc += static_cast<double>(MetaSum<391ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<91, 92, 93, 94>::fold();
    acc += static_cast<double>(Grid<331>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 91.0);
    acc += regex_score("module 091 alpha42 beta tu91");
    return acc / 6.0;
}

}  // namespace cbor
