// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_035() {
    double acc = Polynomial<335>::eval(0.5);
    acc += static_cast<double>(MetaSum<335ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<35, 36, 37, 38>::fold();
    acc += static_cast<double>(Grid<323>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 35.0);
    acc += regex_score("module 035 alpha42 beta tu35");
    return acc / 6.0;
}

}  // namespace cbor
