// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_060() {
    double acc = Polynomial<360>::eval(0.5);
    acc += static_cast<double>(MetaSum<360ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<60, 61, 62, 63>::fold();
    acc += static_cast<double>(Grid<332>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 60.0);
    acc += regex_score("module 060 alpha42 beta tu60");
    return acc / 6.0;
}

}  // namespace cbor
