// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_064() {
    double acc = Polynomial<364>::eval(0.5);
    acc += static_cast<double>(MetaSum<364ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<64, 65, 66, 67>::fold();
    acc += static_cast<double>(Grid<320>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 64.0);
    acc += regex_score("module 064 alpha42 beta tu64");
    return acc / 6.0;
}

}  // namespace cbor
