// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_026() {
    double acc = Polynomial<326>::eval(0.5);
    acc += static_cast<double>(MetaSum<326ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<26, 27, 28, 29>::fold();
    acc += static_cast<double>(Grid<330>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 26.0);
    acc += regex_score("module 026 alpha42 beta tu26");
    return acc / 6.0;
}

}  // namespace cbor
