// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_084() {
    double acc = Polynomial<384>::eval(0.5);
    acc += static_cast<double>(MetaSum<384ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<84, 85, 86, 87>::fold();
    acc += static_cast<double>(Grid<324>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 84.0);
    acc += regex_score("module 084 alpha42 beta tu84");
    return acc / 6.0;
}

}  // namespace cbor
