// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_069() {
    double acc = Polynomial<369>::eval(0.5);
    acc += static_cast<double>(MetaSum<369ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<69, 70, 71, 72>::fold();
    acc += static_cast<double>(Grid<325>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 69.0);
    acc += regex_score("module 069 alpha42 beta tu69");
    return acc / 6.0;
}

}  // namespace cbor
