// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_072() {
    double acc = Polynomial<372>::eval(0.5);
    acc += static_cast<double>(MetaSum<372ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<72, 73, 74, 75>::fold();
    acc += static_cast<double>(Grid<328>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 72.0);
    acc += regex_score("module 072 alpha42 beta tu72");
    return acc / 6.0;
}

}  // namespace cbor
