// AUTO-GENERATED by bench/gen-sources.sh — intentionally heavy translation unit.
#include "common.hpp"
#include "heavy_template.hpp"

namespace cbor {

double compute_module_094() {
    double acc = Polynomial<394>::eval(0.5);
    acc += static_cast<double>(MetaSum<394ULL>::value % 9973ULL) / 9973.0;
    acc += TypePack<94, 95, 96, 97>::fold();
    acc += static_cast<double>(Grid<334>::value & 0xffffL) / 65535.0;
    acc += mix(acc + 94.0);
    acc += regex_score("module 094 alpha42 beta tu94");
    return acc / 6.0;
}

}  // namespace cbor
